SELECT * FROM "public"."SRC";
SELECT SRC.ID FROM "public"."SRC" AS SRC;

INSERT INTO "public".SRC VALUES (1,'A','TEN');
INSERT INTO "public".SRC VALUES (2,'B','NINE');
INSERT INTO "public".SRC VALUES (3,'C','EIGHT');

DELETE FROM SRC WHERE id = 1;
DELETE FROM SRC WHERE id IN (4,3,2);

UPDATE SRC
SET NAME = 'Z',
    MARKS = 'FOUR' 
WHERE
	ID = 1;

DROP TABLE SRC;

CREATE TABLE SRC (
    ID INTEGER,
    NAME VARCHAR(10),
    MARKS VARCHAR(10),
    LOADED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);
